[ITT-556]Regenerated binlookup and fix tests
Adyen/adyen-node-api-library pull request #1176
Opened 2023-06-02 07:56 UTC by jillingk

**Description**
Regenerate binlookup.

2023-06-06 06:54 UTC, wboereboom requested changes
We should also bump the version numbers in the README

2023-06-06 06:54 UTC, wboereboom requested changes
We should also bump the version numbers in the README

2023-06-06 11:34 UTC, michaelpaul submitted a review, later dismissed

2023-06-15 09:52 UTC, michaelpaul submitted a review, later dismissed

2023-06-23 07:40 UTC, wboereboom submitted a review, later dismissed

2023-06-23 08:10 UTC, wboereboom submitted a review, later dismissed

2023-06-23 08:38 UTC, AlexandrosMor submitted a review, later dismissed

2023-06-23 12:17 UTC, antolo-arch approved these changes

2023-06-23 12:21 UTC, AlexandrosMor approved these changes

2023-06-23 12:22 UTC, merged