[ITT-556] Regenerate payout
Adyen/adyen-node-api-library pull request #1178
Opened 2023-06-02 12:27 UTC by jillingk

**Description**
Regenerate payout.

2023-06-06 06:52 UTC, wboereboom requested changes
found a typo

2023-06-06 06:52 UTC, wboereboom commented on Makefile
> +terminalManagement: spec=TfmAPIService-v1m
```suggestion
terminalManagement: spec=TfmAPIService-v1
```

2023-06-06 11:35 UTC, michaelpaul submitted a review, later dismissed

2023-06-23 07:39 UTC, wboereboom approved these changes

2023-06-23 07:41 UTC, merged