Itt 584/automate services
Adyen/adyen-node-api-library pull request #1204
Opened 2023-07-11 06:52 UTC by wboereboom

**Description**
This PR includes definition updates and automation for all service classes

**Tested scenarios**
Through unit tests and manual testing

2023-07-17 11:32 UTC, jillingk commented
Regenerated checkout with older specs, regenerated the rest with recent specs and updated some unit tests. Also added a line to set the config environment variable as merchant can also set the environment in the client. Lastly added two lines to throw an error whenever a live url needs to be set and no liveurlprefix is available.

2023-07-17 14:24 UTC, jillingk submitted a review, later dismissed

2023-07-17 14:59 UTC, michaelpaul requested changes

2023-07-17 14:59 UTC, michaelpaul commented on Makefile
> +balancePlatform: spec=BalancePlatformService-v2
Duplicate line, see line 24.

2023-07-17 14:59 UTC, michaelpaul commented on .github/workflows/services.yml
> +          echo ::set-output name=pr_title::"Update models"
Did you mean "Services"?

2023-07-17 14:59 UTC, michaelpaul commented on src/client.ts
>      public setEnvironment(environment: Environment, liveEndpointUrlPrefix?: string): void {
'liveEndpointUrlPrefix' is defined but never used

2023-07-17 14:59 UTC, michaelpaul commented on src/service.ts
> +                throw new Error("Please provide your unique live url prefix on the setEnvironment() call on the Client.")
Looks like `setEnvironment` is not the way to set live prefix anymore.

2023-07-18 07:43 UTC, michaelpaul approved these changes

2023-07-18 08:08 UTC, merged