update makefile, a readme to upgrade Transfers and Management API
Adyen/adyen-node-api-library pull request #1235
Opened 2023-08-18 13:03 UTC by Aleffio

**Description**
This PR upgrades:

- Transfers service from v3 to v4
- Management service from v1 to v3

2023-08-18 14:16 UTC, michaelpaul submitted a review, later dismissed

2023-08-21 14:56 UTC, michaelpaul requested changes
WIP

2023-10-23 09:05 UTC, michaelpaul approved these changes

2023-10-23 09:10 UTC, jillingk approved these changes

2023-10-23 09:17 UTC, merged