Add Support For Local Unencrypted TAPI
Adyen/adyen-node-api-library pull request #1244
Opened 2023-09-01 12:56 UTC by jillingk

**Description**
This pr adds support for the local terminal api without encryption. This is tested with a test terminal.

2023-09-01 14:03 UTC, wboereboom submitted a review, later dismissed

2023-09-04 01:58 UTC, michaelpaul requested changes

2023-09-04 01:58 UTC, michaelpaul commented on README.md
> +In case you would like to develop the Local Terminal API integration parallel to you encryption implementation, you can opt for the unencrypted version. Be sure to remove any encryption details from
```suggestion
If you wish to develop the Local Terminal API integration parallel to your encryption implementation, you can opt for the unencrypted version. Be sure to remove any encryption details from the CA terminal config page. 
```

2023-09-04 02:21 UTC, michaelpaul approved these changes

2023-09-04 07:37 UTC, wboereboom approved these changes

2023-09-04 07:37 UTC, merged