Fix version calculation based on PR labels
Adyen/adyen-node-api-library pull request #1258
Opened 2023-09-27 08:06 UTC by AlexandrosMor

**Description**

Fix version calculation based on PR labels
**Tested scenarios**

**Fixed issue**:

2023-09-27 08:20 UTC, michaelpaul commented on .github/scripts/release.test.js
> +  await t.test('Major', t => {
```suggestion
  await t.test('Minor', t => {
```

2023-09-27 08:26 UTC, michaelpaul approved these changes

2023-09-27 08:47 UTC, wboereboom requested changes
Maybe we can find a more intuitive way rather than triple for loop.

2023-09-27 17:07 UTC, AlexandrosMor commented
@wboereboom could you review again ? As we discussed for now is not worth the effort to refactor that part

2023-09-28 10:12 UTC, wboereboom approved these changes

2023-09-28 11:01 UTC, merged