PW-6668: POS Terminal Management API
Adyen/adyen-node-api-library pull request #922
Opened 2022-07-12 13:04 UTC by michaelpaul

**Description**

This PR adds support for [POS Terminal Management API](https://docs.adyen.com/api-explorer/#/postfmapi/v1/overview) into the library. 

**Tested scenarios**
* unit tests

2022-07-15 06:46 UTC, wboereboom requested changes
Left a single comment. A bit nitpicky, because all the rest looks solid  💪

2022-07-15 06:46 UTC, wboereboom commented on src/__tests__/terminalManagement.spec.ts
> +import { AssignTerminalsRequest } from "../typings/terminalManagement/assignTerminalsRequest";
consider importing the models from the model.ts file rather than including all individual model files.

2022-07-26 12:02 UTC, wboereboom submitted a review, later dismissed

2022-07-27 08:45 UTC, wboereboom approved these changes

2022-08-04 13:05 UTC, AlexandrosMor approved these changes

2022-08-04 13:10 UTC, merged