Updating dependabot reviewers
Adyen/adyen-node-api-library pull request #966
Opened 2022-08-18 11:14 UTC by acampos1916

Hi @msilvagarcia 👋

2022-08-18 11:18 UTC, wboereboom approved these changes

2022-08-18 13:58 UTC, msilvagarcia requested changes
Use the imperative mood on commit messages and pull request title :)

2022-08-18 15:02 UTC, peterojo submitted a review, later dismissed

2022-08-19 07:16 UTC, acampos1916 commented
> Use the imperative mood on commit messages and pull request title :)

😄 Thanks for the review!

2022-08-19 14:34 UTC, merged

2022-08-22 17:21 UTC, msilvagarcia commented
> > Use the imperative mood on commit messages and pull request title :)
> 
> 😄 Thanks for the review!

Thanks for listening :)